---
- name: Retrying a task until a condition is met
  hosts: all
  become: true
  tasks:
  - name: Retry a task until a certain condition is met
    shell: /usr/bin/foo
    register: result
    until: result.stdout.find("all systems go") != -1
    retries: 5
    delay: 10