---
- name: Iterating over a list of dictionaries
  hosts: all
  become: yes
  tasks:
   - name: Create new user
     user:
      name: '{{ item.name }}'
      uid: '{{ item.uid }}'
      state: present

     loop:
       - { name: john , uid: 1020 }
       - { name: mike , uid: 1030 }
       - { name: andrew , uid: 1040 }