---
- name: Ansible loops with indexes
  hosts: all
  become: yes
  tasks:
   - name: Indexes with ansible loop
     debug:
       msg: "The car at {{ item.0 }} is {{ item.1 }}"
     with_indexed_items:
       - "Nissan"
       - "Mercedes"
       - "Toyota"
       - "Mazda"
       - "BMW"