- hosts: all
  tasks:
    - name: Ansible template inventory collection example.
      template:
        src: inventory.j2
        dest: /var/tmp/{{ ansible_nodename }}_inventory.txt
        mode: 0777