---
# tasks file for container
- name: Update all packages
  apt:
    upgrade: dist

- name: Check if Docker exists
  shell: dpkg -l | grep -E "docker.io|containerd"
  register: packageCheck
  ignore_errors: yes

- name: Ensure Docker is installed
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  when: packageCheck.rc != 0 

# Mention base image pull configuration below
- name: Pull SonarQube image
  docker_image:
    name: sonarqube
    source: pull
    tag: "8.9-community"

- name: Pull Splunk enterprise image
  docker_image:
    name: splunk/splunk
    source: pull
    tag: "latest"

- name: Pull Redis image
  docker_image:
    name: redis
    source: pull
    tag: "7.2.4"

- name: Pull Jenkins image
  docker_image:
    name: jenkins/jenkins
    source: pull
    tag: "lts"

# Mention container configuration below
- name: Run SonarQube container
  docker_container:
    name: sonarqube-dev
    image: sonarqube:8.9-community
    published_ports:
      - "9000:9000"
    memory: "2g"
    state: started

- name: Run Splunk container
  docker_container:
    name: splunk-dev
    image: splunk/splunk:latest
    published_ports:
      - "8000:8000"
    memory: "4g"
    state: stopped
    env:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "Password1!"

- name: Run Redis container
  docker_container:
    name: redis-dev
    image: redis:7.2.4
    command: redis-server --appendonly yes
    published_ports:
      - "6379:6379"
    state: stopped

- name: Run Jenkins container
  docker_container:
    name: jenkins-dev
    image: jenkins/jenkins:lts
    published_ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - "jenkins_volume:/var/jenkins_home"
    state: stopped
