---
- name: Copy content to a file
  hosts: all
  gather_facts: true
  tasks:
    - name: Create a file and copy content
      copy:
        dest: /var/tmp/syslog.html
        content: |
          {{ ansible_hostname }}
          {{ ansible_default_ipv4.address | default('Not available') }}
          {{ ansible_default_ipv4.macaddress | default('Not available') }}
        mode: "0644"
