---
- name: install nginx
  apt:
    name: nginx
    state: latest

- name: start nginx service
  service:
    name: nginx
    state: restarted
    enabled: yes

- name: create vhost directory
  file:
    path: /var/www/html/vhosts/
    state: directory

- name: copy the html file
  copy:
    src: index.html
    dest: "/var/www/html/vhosts/{{ ansible_hostname }}"

- name: vhost template file
  template:
    src: vhost.conf.j2
    dest: /etc/nginx/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx
