---
# tasks file for sonarqube
- name: Update all packages
  apt:
    upgrade: dist

- name: Check if Docker exists
  shell: dpkg -l | grep -E "docker.io|containerd"
  register: packageCheck
  ignore_errors: yes

- name: Ensure Docker in installed
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  when: packageCheck.rc != 0 

# Mention base image pull configuration below
- name: Pull SonarQube image
  docker_image:
    name: sonarqube
    source: pull
    tag: "8.9-community"

- name: Pull Splunk enterprise image
  docker_image:
    name: splunk/splunk
    source: pull
    tag: "latest"

- name: Pull Nexus repository image
  docker_image:
    name: dockette/nexus
    source: pull
    tag: "3.69.0"

# Mention container configuration below
- name: Run SonarQube container
  docker_container:
    name: sonarqube-dev
    image: sonarqube:8.9-community
    published_ports:
      - "9000:9000"
    memory: "2g"
    state: started

- name: Run Splunk container
  docker_container:
    name: splunk-dev
    image: splunk/splunk:latest
    published_ports:
      - "8000:8000"
    memory: "4g"
    state: started
    env:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD: "Password1!"

- name: Run Nexus container
  docker_container:
    name: nexus-dev
    image: dockette/nexus:3.69.0
    published_ports:
      - "8081:8081"
    memory: "4g"
    state: started