---
- hosts: all
  become: yes
  tasks:
   - name: Making sure the /tmp has more than 1gb
     shell: "df -h /tmp|grep -v Filesystem | awk '{print$4}' | cut -d G -f1"
     register: tmpspace
     failed_when: "tmpspace.stdout | float < 1"

   - name: Making sure the /run has more than 1gb
     shell: "df -h /run | grep -v Filesystem | awk '{print$5}' | cut -d % -f1"
     register: runspace
     failed_when: "runspace.stdout | float > 75"

   - name: Making sure the Physical Memory less than 2gb
     shell: "cat /proc/meminfo|grep -i memtotal|awk '{print $2/1024/1024}'"
     register: memory
     failed_when: "memory.stdout|float > 2"

   - debug:
      msg: >-
       /tmp space is {{ tmpspace.stdout }}gb.
       /run space is {{ runspace.stdout }}gb.
       Physical memory is {{ memory.stdout }}gb.