---
- hosts: all
  become: yes
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start NGINX
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy files across hosts
      copy:
        src: "test.txt"
        dest: "~/"

